# Configuration file for the DWI preprocessing pipeline
# This file contains the necessary parameters for running the `sct_run_batch` command

# Path to the raw pediatric dataset
path_data: 

# Path to the output results
path_output: 

# Number of parallel jobs (-1 uses all CPU cores minus one)
jobs: -1