# Configuration file for data preprocessing
# This file contains the necessary parameters for running the `sct_run_batch` command

# Path to the pediatric dataset
path_data:

# Number of parallel jobs (-1 uses all CPU cores minus one)
jobs: -1